name: Talent Academy Demo
on: [ push ]    # List on one line
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    steps: # The list of steps to take for executionnn
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Clone your code in the pipeline
        uses: actions/checkout@v2 

      - name: Echo private key
        run: |
          mkdir ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # - name: Decrypt Pem
      #   run: ./decrypt_secret.sh
      #   env:
      #     LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      # - name: Test printing your secret (Remove this step in production)
      #   run: cat $HOME/secrets/ta-lab-key.pem

      # - name: Convert ssh key to file      
      #   uses: webfactory/ssh-agent@v0.5.2
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          

      - name: Checking ssh connection
        uses: fifsky/ssh-action@master
        with:
          host: 34.243.110.224
          user: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY}}

      # - name: Run playbook
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     # Required, playbook filepath
      #     playbook: playbook.yml
      #     # Optional, directory where playbooks live
      #     directory: ./
      #     # Optional, SSH private key
      #     key: ${{secrets.SSH_PRIVATE_KEY}}
      #     # Optional, literal inventory file contents
      #     inventory: inventory.hosts
            
          # Optional, SSH known hosts file content
          # known_hosts: .known_hosts
          # Optional, encrypted vault password
          # vault_password: ${{secrets.VAULT_PASSWORD}}
          # Optional, galaxy requirements filepath
          # requirements: galaxy-requirements.yml
          # Optional, additional flags to pass to ansible-playbook
          

      # - name: Running our playbook
      #   uses: saubermacherag/ansible-playbook-docker-action@v1.4
      #   with:
      #     playbookName: 'playbook.yml'
      #     inventoryFile: 'inventory.hosts'
          # keyFile: $HOME/secrets/ta-lab-key.pem

      - name: Run playbook to configure nginx 
        id: run_playbook
        run: ansible-playbook playbook.yml 
        continue-on-error: true
